package org.dyndns.jkiddo.dmp;

public interface IDmapProtocolDefinition
{
	public enum DmapTypeDefinition
	{
		U_BYTE_TYPE(1,1 ),
		BYTE_TYPE(2,1 ),
		U_SHORT_TYPE(3,2 ),
		SHORT_TYPE(4,2 ),
		U_INT_TYPE(5,4 ),
		INT_TYPE(6,4 ),
		U_LONG_TYPE(7,8 ),
		LONG_TYPE(8,8 ),
		STRING_TYPE(9,-1 ),
		DATE_TYPE(10,4 ),
		VERSION_TYPE(11,4 ),
		CONTAINER_TYPE(12,-1 ),
		RAW_TYPE(13,-1 );

		private int type;
		private int length;

		DmapTypeDefinition(int type, int length)
		{
			this.type = type;
			this.length = length;
		}
	}
	public static enum DmapProtocolDefinition implements IDmapProtocolDefinition
	{
		aeCS("aeCS","com.apple.itunes.artworkchecksum",DmapTypeDefinition.U_INT_TYPE),
		aeGs("aeGs","com.apple.itunes.can-be-genius-seed",DmapTypeDefinition.U_BYTE_TYPE),
		aeCF("aeCF","com.apple.itunes.cloud-flavor-id",DmapTypeDefinition.U_LONG_TYPE),
		aeCd("aeCd","com.apple.itunes.cloud-id",DmapTypeDefinition.U_LONG_TYPE),
		aeCK("aeCK","com.apple.itunes.cloud-library-kind",DmapTypeDefinition.U_BYTE_TYPE),
		aeCM("aeCM","com.apple.itunes.cloud-status",DmapTypeDefinition.U_BYTE_TYPE),
		aeCU("aeCU","com.apple.itunes.cloud-user-id",DmapTypeDefinition.U_LONG_TYPE),
		aeCR("aeCR","com.apple.itunes.content-rating",DmapTypeDefinition.STRING_TYPE),
		aeK1("aeK1","com.apple.itunes.drm-key1-id",DmapTypeDefinition.U_LONG_TYPE),
		aeK2("aeK2","com.apple.itunes.drm-key2-id",DmapTypeDefinition.U_LONG_TYPE),
		aeDP("aeDP","com.apple.itunes.drm-platform-id",DmapTypeDefinition.U_INT_TYPE),
		aeDR("aeDR","com.apple.itunes.drm-user-id",DmapTypeDefinition.U_LONG_TYPE),
		aeDV("aeDV","com.apple.itunes.drm-versions",DmapTypeDefinition.U_INT_TYPE),
		aeEN("aeEN","com.apple.itunes.episode-num-str",DmapTypeDefinition.STRING_TYPE),
		aeES("aeES","com.apple.itunes.episode-sort",DmapTypeDefinition.U_INT_TYPE),
		aeMk("aeMk","com.apple.itunes.extended-media-kind",DmapTypeDefinition.U_INT_TYPE),
		aeGU("aeGU","com.apple.itunes.gapless-dur",DmapTypeDefinition.U_LONG_TYPE),
		aeGE("aeGE","com.apple.itunes.gapless-enc-del",DmapTypeDefinition.U_INT_TYPE),
		aeGD("aeGD","com.apple.itunes.gapless-enc-dr",DmapTypeDefinition.U_INT_TYPE),
		aeGH("aeGH","com.apple.itunes.gapless-heur",DmapTypeDefinition.U_INT_TYPE),
		aeGR("aeGR","com.apple.itunes.gapless-resy",DmapTypeDefinition.U_LONG_TYPE),
		ceGS("ceGS","com.apple.itunes.genius-selectable",DmapTypeDefinition.U_BYTE_TYPE),
		aeHV("aeHV","com.apple.itunes.has-video",DmapTypeDefinition.U_BYTE_TYPE),
		aeHD("aeHD","com.apple.itunes.is-hd-video",DmapTypeDefinition.U_BYTE_TYPE),
		aePC("aePC","com.apple.itunes.is-podcast",DmapTypeDefinition.U_BYTE_TYPE),
		aePP("aePP","com.apple.itunes.is-podcast-playlist",DmapTypeDefinition.U_BYTE_TYPE),
		aeAI("aeAI","com.apple.itunes.itms-artistid",DmapTypeDefinition.U_INT_TYPE),
		aeCI("aeCI","com.apple.itunes.itms-composerid",DmapTypeDefinition.U_INT_TYPE),
		aeGI("aeGI","com.apple.itunes.itms-genreid",DmapTypeDefinition.U_INT_TYPE),
		aePI("aePI","com.apple.itunes.itms-playlistid",DmapTypeDefinition.U_INT_TYPE),
		aeSI("aeSI","com.apple.itunes.itms-songid",DmapTypeDefinition.U_INT_TYPE),
		aeSF("aeSF","com.apple.itunes.itms-storefrontid",DmapTypeDefinition.U_INT_TYPE),
		aeMK("aeMK","com.apple.itunes.mediakind",DmapTypeDefinition.U_BYTE_TYPE),
		aeMX("aeMX","com.apple.itunes.movie-info-xml",DmapTypeDefinition.STRING_TYPE),
		aeSV("aeSV","com.apple.itunes.music-sharing-version",DmapTypeDefinition.U_INT_TYPE),
		aeNN("aeNN","com.apple.itunes.network-name",DmapTypeDefinition.STRING_TYPE),
		aeND("aeND","com.apple.itunes.non-drm-user-id",DmapTypeDefinition.U_LONG_TYPE),
		aeNV("aeNV","com.apple.itunes.norm-volume",DmapTypeDefinition.U_INT_TYPE),
		ceQa("ceQa","com.apple.itunes.playqueue-album",DmapTypeDefinition.STRING_TYPE),
		ceQr("ceQr","com.apple.itunes.playqueue-artist",DmapTypeDefinition.STRING_TYPE),
		ceQS("ceQS","com.apple.itunes.playqueue-content-unknown",DmapTypeDefinition.CONTAINER_TYPE),
		ceQR("ceQR","com.apple.itunes.playqueue-contents-response",DmapTypeDefinition.CONTAINER_TYPE),
		ceQg("ceQg","com.apple.itunes.playqueue-genre",DmapTypeDefinition.STRING_TYPE),
		ceQs("ceQs","com.apple.itunes.playqueue-id",DmapTypeDefinition.U_LONG_TYPE),
		ceQn("ceQn","com.apple.itunes.playqueue-name",DmapTypeDefinition.STRING_TYPE),
		____("____","com.apple.itunes.req-fplay",DmapTypeDefinition.U_BYTE_TYPE),
		aeSG("aeSG","com.apple.itunes.saved-genius",DmapTypeDefinition.U_BYTE_TYPE),
		ceSG("ceSG","com.apple.itunes.saved-genius",DmapTypeDefinition.U_BYTE_TYPE),
		aeSU("aeSU","com.apple.itunes.season-num",DmapTypeDefinition.U_INT_TYPE),
		aeSN("aeSN","com.apple.itunes.series-name",DmapTypeDefinition.STRING_TYPE),
		aeSP("aeSP","com.apple.itunes.smart-playlist",DmapTypeDefinition.U_BYTE_TYPE),
		aePS("aePS","com.apple.itunes.special-playlist",DmapTypeDefinition.U_BYTE_TYPE),
		aeSE("aeSE","com.apple.itunes.store-pers-id",DmapTypeDefinition.U_LONG_TYPE),
		//aeCS("aeCS","com.apple.itunes.unknown-CS",DmapTypeDefinition.U_INT_TYPE),
		aeFP("aeFP","com.apple.itunes.unknown-FP",DmapTypeDefinition.U_BYTE_TYPE),
		aeFR("aeFR","com.apple.itunes.unknown-FR",DmapTypeDefinition.U_BYTE_TYPE),
		aeIM("aeIM","com.apple.itunes.unknown-IM",DmapTypeDefinition.U_LONG_TYPE),
		aeMQ("aeMQ","com.apple.itunes.unknown-MQ",DmapTypeDefinition.U_BYTE_TYPE),
		ceQu("ceQu","com.apple.itunes.unknown-Qu",DmapTypeDefinition.U_BYTE_TYPE),
		aeRM("aeRM","com.apple.itunes.unknown-RM",DmapTypeDefinition.U_LONG_TYPE),
		aeSL("aeSL","com.apple.itunes.unknown-SL",DmapTypeDefinition.U_BYTE_TYPE),
		aeSR("aeSR","com.apple.itunes.unknown-SR",DmapTypeDefinition.U_BYTE_TYPE),
		aeSX("aeSX","com.apple.itunes.unknown-SX",DmapTypeDefinition.U_LONG_TYPE),
		aeTr("aeTr","com.apple.itunes.unknown-Tr",DmapTypeDefinition.U_BYTE_TYPE),
		agal("agal","com.apple.itunes.unknown-al",DmapTypeDefinition.CONTAINER_TYPE),
		msed("msed","com.apple.itunes.unknown-ed",DmapTypeDefinition.U_BYTE_TYPE),
		caip("caip","com.apple.itunes.unknown-ip",DmapTypeDefinition.U_BYTE_TYPE),
		caiv("caiv","com.apple.itunes.unknown-iv",DmapTypeDefinition.U_BYTE_TYPE),
		msma("msma","com.apple.itunes.unknown-ma",DmapTypeDefinition.U_LONG_TYPE),
		msml("msml","com.apple.itunes.unknown-ml",DmapTypeDefinition.CONTAINER_TYPE),
		cmpg("cmpg","com.apple.itunes.unknown-pg",DmapTypeDefinition.RAW_TYPE),
		casa("casa","com.apple.itunes.unknown-sa",DmapTypeDefinition.U_INT_TYPE),
		asse("asse","com.apple.itunes.unknown-se",DmapTypeDefinition.U_LONG_TYPE),
		casu("casu","com.apple.itunes.unknown-su",DmapTypeDefinition.U_BYTE_TYPE),
		cavd("cavd","com.apple.itunes.unknown-vd",DmapTypeDefinition.U_BYTE_TYPE),
		aeXD("aeXD","com.apple.itunes.xid",DmapTypeDefinition.STRING_TYPE),
		abpl("abpl","daap.baseplaylist",DmapTypeDefinition.U_BYTE_TYPE),
		asbk("asbk","daap.bookmarkable",DmapTypeDefinition.U_BYTE_TYPE),
		abal("abal","daap.browsealbumlisting",DmapTypeDefinition.CONTAINER_TYPE),
		abar("abar","daap.browseartistlisting",DmapTypeDefinition.CONTAINER_TYPE),
		abcp("abcp","daap.browsecomposerlisting",DmapTypeDefinition.CONTAINER_TYPE),
		abgn("abgn","daap.browsegenrelisting",DmapTypeDefinition.CONTAINER_TYPE),
		abro("abro","daap.databasebrowse",DmapTypeDefinition.CONTAINER_TYPE),
		aply("aply","daap.databaseplaylists",DmapTypeDefinition.CONTAINER_TYPE),
		adbs("adbs","daap.databasesongs",DmapTypeDefinition.CONTAINER_TYPE),
		agac("agac","daap.groupalbumcount",DmapTypeDefinition.U_INT_TYPE),
		aprm("aprm","daap.playlistrepeatmode",DmapTypeDefinition.U_BYTE_TYPE),
		apsm("apsm","daap.playlistshufflemode",DmapTypeDefinition.U_BYTE_TYPE),
		apso("apso","daap.playlistsongs",DmapTypeDefinition.CONTAINER_TYPE),
		apro("apro","daap.protocolversion",DmapTypeDefinition.VERSION_TYPE),
		arsv("arsv","daap.resolve",DmapTypeDefinition.CONTAINER_TYPE),
		arif("arif","daap.resolveinfo",DmapTypeDefinition.CONTAINER_TYPE),
		avdb("avdb","daap.serverdatabases",DmapTypeDefinition.CONTAINER_TYPE),
		asal("asal","daap.songalbum",DmapTypeDefinition.STRING_TYPE),
		asaa("asaa","daap.songalbumartist",DmapTypeDefinition.STRING_TYPE),
		asai("asai","daap.songalbumid",DmapTypeDefinition.U_LONG_TYPE),
		aslr("aslr","daap.songalbumuserrating",DmapTypeDefinition.U_BYTE_TYPE),
		asas("asas","daap.songalbumuserratingstatus",DmapTypeDefinition.U_BYTE_TYPE),
		asar("asar","daap.songartist",DmapTypeDefinition.STRING_TYPE),
		asri("asri","daap.songartistid",DmapTypeDefinition.U_LONG_TYPE),
		asac("asac","daap.songartworkcount",DmapTypeDefinition.U_SHORT_TYPE),
		asbt("asbt","daap.songbeatsperminute",DmapTypeDefinition.U_SHORT_TYPE),
		asbr("asbr","daap.songbitrate",DmapTypeDefinition.U_SHORT_TYPE),
		asct("asct","daap.songcategory",DmapTypeDefinition.STRING_TYPE),
		ascs("ascs","daap.songcodecsubtype",DmapTypeDefinition.U_INT_TYPE),
		ascd("ascd","daap.songcodectype",DmapTypeDefinition.U_INT_TYPE),
		ascm("ascm","daap.songcomment",DmapTypeDefinition.STRING_TYPE),
		asco("asco","daap.songcompilation",DmapTypeDefinition.U_BYTE_TYPE),
		ascp("ascp","daap.songcomposer",DmapTypeDefinition.STRING_TYPE),
		ascn("ascn","daap.songcontentdescription",DmapTypeDefinition.STRING_TYPE),
		ascr("ascr","daap.songcontentrating",DmapTypeDefinition.U_BYTE_TYPE),
		asdk("asdk","daap.songdatakind",DmapTypeDefinition.U_BYTE_TYPE),
		asul("asul","daap.songdataurl",DmapTypeDefinition.STRING_TYPE),
		asda("asda","daap.songdateadded",DmapTypeDefinition.DATE_TYPE),
		asdm("asdm","daap.songdatemodified",DmapTypeDefinition.DATE_TYPE),
		aspl("aspl","daap.songdateplayed",DmapTypeDefinition.DATE_TYPE),
		asdp("asdp","daap.songdatepurchased",DmapTypeDefinition.DATE_TYPE),
		asdr("asdr","daap.songdatereleased",DmapTypeDefinition.DATE_TYPE),
		asdt("asdt","daap.songdescription",DmapTypeDefinition.STRING_TYPE),
		asdb("asdb","daap.songdisabled",DmapTypeDefinition.U_BYTE_TYPE),
		asdc("asdc","daap.songdisccount",DmapTypeDefinition.U_SHORT_TYPE),
		asdn("asdn","daap.songdiscnumber",DmapTypeDefinition.U_SHORT_TYPE),
		aseq("aseq","daap.songeqpreset",DmapTypeDefinition.STRING_TYPE),
		ases("ases","daap.songexcludefromshuffle",DmapTypeDefinition.U_BYTE_TYPE),
		ased("ased","daap.songextradata",DmapTypeDefinition.U_SHORT_TYPE),
		asfm("asfm","daap.songformat",DmapTypeDefinition.STRING_TYPE),
		asgp("asgp","daap.songgapless",DmapTypeDefinition.U_BYTE_TYPE),
		asgn("asgn","daap.songgenre",DmapTypeDefinition.STRING_TYPE),
		agrp("agrp","daap.songgrouping",DmapTypeDefinition.STRING_TYPE),
		ashp("ashp","daap.songhasbeenplayed",DmapTypeDefinition.U_BYTE_TYPE),
		asky("asky","daap.songkeywords",DmapTypeDefinition.STRING_TYPE),
		askd("askd","daap.songlastskipdate",DmapTypeDefinition.DATE_TYPE),
		aslc("aslc","daap.songlongcontentdescription",DmapTypeDefinition.STRING_TYPE),
		asls("asls","daap.songlongsize",DmapTypeDefinition.U_LONG_TYPE),
		aspu("aspu","daap.songpodcasturl",DmapTypeDefinition.STRING_TYPE),
		asrv("asrv","daap.songrelativevolume",DmapTypeDefinition.BYTE_TYPE),
		assr("assr","daap.songsamplerate",DmapTypeDefinition.U_INT_TYPE),
		assz("assz","daap.songsize",DmapTypeDefinition.U_INT_TYPE),
		asst("asst","daap.songstarttime",DmapTypeDefinition.U_INT_TYPE),
		assp("assp","daap.songstoptime",DmapTypeDefinition.U_INT_TYPE),
		astm("astm","daap.songtime",DmapTypeDefinition.U_INT_TYPE),
		astc("astc","daap.songtrackcount",DmapTypeDefinition.U_SHORT_TYPE),
		astn("astn","daap.songtracknumber",DmapTypeDefinition.U_SHORT_TYPE),
		aspc("aspc","daap.songuserplaycount",DmapTypeDefinition.U_INT_TYPE),
		asur("asur","daap.songuserrating",DmapTypeDefinition.U_BYTE_TYPE),
		asrs("asrs","daap.songuserratingstatus",DmapTypeDefinition.U_BYTE_TYPE),
		askp("askp","daap.songuserskipcount",DmapTypeDefinition.U_INT_TYPE),
		asyr("asyr","daap.songyear",DmapTypeDefinition.U_SHORT_TYPE),
		assu("assu","daap.sortalbum",DmapTypeDefinition.STRING_TYPE),
		assl("assl","daap.sortalbumartist",DmapTypeDefinition.STRING_TYPE),
		assa("assa","daap.sortartist",DmapTypeDefinition.STRING_TYPE),
		assc("assc","daap.sortcomposer",DmapTypeDefinition.STRING_TYPE),
		assn("assn","daap.sortname",DmapTypeDefinition.STRING_TYPE),
		asss("asss","daap.sortseriesname",DmapTypeDefinition.STRING_TYPE),
		ated("ated","daap.supportsextradata",DmapTypeDefinition.U_SHORT_TYPE),
		asgr("asgr","daap.supportsgroups",DmapTypeDefinition.U_SHORT_TYPE),
		caar("caar","dacp.availablerepeatstates",DmapTypeDefinition.U_INT_TYPE),
		caas("caas","dacp.availableshufflestates",DmapTypeDefinition.U_INT_TYPE),
		caci("caci","dacp.controlint",DmapTypeDefinition.CONTAINER_TYPE),
		cafs("cafs","dacp.fullscreen",DmapTypeDefinition.U_BYTE_TYPE),
		cafe("cafe","dacp.fullscreenenabled",DmapTypeDefinition.U_BYTE_TYPE),
		caia("caia","dacp.isactive",DmapTypeDefinition.U_BYTE_TYPE),
		canl("canl","dacp.nowplayingalbum",DmapTypeDefinition.STRING_TYPE),
		cana("cana","dacp.nowplayingartist",DmapTypeDefinition.STRING_TYPE),
		cang("cang","dacp.nowplayinggenre",DmapTypeDefinition.STRING_TYPE),
		canp("canp","dacp.nowplayingids",DmapTypeDefinition.RAW_TYPE),
		cann("cann","dacp.nowplayingname",DmapTypeDefinition.STRING_TYPE),
		cant("cant","dacp.nowplayingtime",DmapTypeDefinition.U_INT_TYPE),
		caps("caps","dacp.playerstate",DmapTypeDefinition.U_BYTE_TYPE),
		capr("capr","dacp.protocolversion",DmapTypeDefinition.VERSION_TYPE),
		carp("carp","dacp.repeatstate",DmapTypeDefinition.U_BYTE_TYPE),
		cash("cash","dacp.shufflestate",DmapTypeDefinition.U_BYTE_TYPE),
		cast("cast","dacp.songtime",DmapTypeDefinition.U_INT_TYPE),
		casp("casp","dacp.speakers",DmapTypeDefinition.CONTAINER_TYPE),
		cavs("cavs","dacp.visualizer",DmapTypeDefinition.U_BYTE_TYPE),
		cave("cave","dacp.visualizerenabled",DmapTypeDefinition.U_BYTE_TYPE),
		cavc("cavc","dacp.volumecontrollable",DmapTypeDefinition.U_INT_TYPE),
		msau("msau","dmap.authenticationmethod",DmapTypeDefinition.U_BYTE_TYPE),
		msas("msas","dmap.authenticationschemes",DmapTypeDefinition.U_BYTE_TYPE),
		mbcl("mbcl","dmap.bag",DmapTypeDefinition.CONTAINER_TYPE),
		mcon("mcon","dmap.container",DmapTypeDefinition.CONTAINER_TYPE),
		mctc("mctc","dmap.containercount",DmapTypeDefinition.U_INT_TYPE),
		mcti("mcti","dmap.containeritemid",DmapTypeDefinition.U_INT_TYPE),
		mcna("mcna","dmap.contentcodesname",DmapTypeDefinition.STRING_TYPE),
		mcnm("mcnm","dmap.contentcodesnumber",DmapTypeDefinition.U_INT_TYPE),
		mccr("mccr","dmap.contentcodesresponse",DmapTypeDefinition.CONTAINER_TYPE),
		mcty("mcty","dmap.contentcodestype",DmapTypeDefinition.U_SHORT_TYPE),
		msdc("msdc","dmap.databasescount",DmapTypeDefinition.U_INT_TYPE),
		mdbk("mdbk","dmap.databasesharetype",DmapTypeDefinition.U_INT_TYPE),
		mudl("mudl","dmap.deletedidlisting",DmapTypeDefinition.CONTAINER_TYPE),
		mdcl("mdcl","dmap.dictionary",DmapTypeDefinition.CONTAINER_TYPE),
		mdst("mdst","dmap.downloadstatus",DmapTypeDefinition.U_BYTE_TYPE),
		meds("meds","dmap.editcommandssupported",DmapTypeDefinition.U_INT_TYPE),
		f_ch("f_ch","dmap.haschildcontainers",DmapTypeDefinition.U_BYTE_TYPE),
		mimc("mimc","dmap.itemcount",DmapTypeDefinition.U_INT_TYPE),
		miid("miid","dmap.itemid",DmapTypeDefinition.U_INT_TYPE),
		mikd("mikd","dmap.itemkind",DmapTypeDefinition.U_BYTE_TYPE),
		minm("minm","dmap.itemname",DmapTypeDefinition.STRING_TYPE),
		mlcl("mlcl","dmap.listing",DmapTypeDefinition.CONTAINER_TYPE),
		mlit("mlit","dmap.listingitem",DmapTypeDefinition.CONTAINER_TYPE),
		mslr("mslr","dmap.loginrequired",DmapTypeDefinition.U_BYTE_TYPE),
		mlog("mlog","dmap.loginresponse",DmapTypeDefinition.CONTAINER_TYPE),
		mpco("mpco","dmap.parentcontainerid",DmapTypeDefinition.U_INT_TYPE),
		mper("mper","dmap.persistentid",DmapTypeDefinition.U_LONG_TYPE),
		mpro("mpro","dmap.protocolversion",DmapTypeDefinition.VERSION_TYPE),
		mrpr("mrpr","dmap.remotepersistentid",DmapTypeDefinition.U_LONG_TYPE),
		mrco("mrco","dmap.returnedcount",DmapTypeDefinition.U_INT_TYPE),
		msrv("msrv","dmap.serverinforesponse",DmapTypeDefinition.CONTAINER_TYPE),
		musr("musr","dmap.serverrevision",DmapTypeDefinition.U_INT_TYPE),
		mlid("mlid","dmap.sessionid",DmapTypeDefinition.U_INT_TYPE),
		mshc("mshc","dmap.sortingheaderchar",DmapTypeDefinition.U_SHORT_TYPE),
		mshi("mshi","dmap.sortingheaderindex",DmapTypeDefinition.U_INT_TYPE),
		mshl("mshl","dmap.sortingheaderlisting",DmapTypeDefinition.CONTAINER_TYPE),
		mshn("mshn","dmap.sortingheadernumber",DmapTypeDefinition.U_INT_TYPE),
		mtco("mtco","dmap.specifiedtotalcount",DmapTypeDefinition.U_INT_TYPE),
		mstt("mstt","dmap.status",DmapTypeDefinition.U_INT_TYPE),
		msts("msts","dmap.statusstring",DmapTypeDefinition.STRING_TYPE),
		msal("msal","dmap.supportsautologout",DmapTypeDefinition.U_BYTE_TYPE),
		msbr("msbr","dmap.supportsbrowse",DmapTypeDefinition.U_BYTE_TYPE),
		msex("msex","dmap.supportsextensions",DmapTypeDefinition.U_BYTE_TYPE),
		msix("msix","dmap.supportsindex",DmapTypeDefinition.U_BYTE_TYPE),
		mspi("mspi","dmap.supportspersistentids",DmapTypeDefinition.U_BYTE_TYPE),
		msqy("msqy","dmap.supportsquery",DmapTypeDefinition.U_BYTE_TYPE),
		msrs("msrs","dmap.supportsresolve",DmapTypeDefinition.U_BYTE_TYPE),
		msup("msup","dmap.supportsupdate",DmapTypeDefinition.U_BYTE_TYPE),
		mstm("mstm","dmap.timeoutinterval",DmapTypeDefinition.U_INT_TYPE),
		mupd("mupd","dmap.updateresponse",DmapTypeDefinition.CONTAINER_TYPE),
		muty("muty","dmap.updatetype",DmapTypeDefinition.U_BYTE_TYPE),
		msto("msto","dmap.utcoffset",DmapTypeDefinition.INT_TYPE),
		mstc("mstc","dmap.utctime",DmapTypeDefinition.DATE_TYPE),
		cmgt("cmgt","dmcp.getpropertyresponse",DmapTypeDefinition.CONTAINER_TYPE),
		cmmk("cmmk","dmcp.mediakind",DmapTypeDefinition.U_INT_TYPE),
		cmst("cmst","dmcp.playstatus",DmapTypeDefinition.CONTAINER_TYPE),
		cmpr("cmpr","dmcp.protocolversion",DmapTypeDefinition.VERSION_TYPE),
		cmsr("cmsr","dmcp.serverrevision",DmapTypeDefinition.U_INT_TYPE),
		cmvo("cmvo","dmcp.volume",DmapTypeDefinition.U_INT_TYPE),
		pasp("pasp","dpap.aspectratio",DmapTypeDefinition.STRING_TYPE),
		picd("picd","dpap.creationdate",DmapTypeDefinition.DATE_TYPE),
		pfdt("pfdt","dpap.filedata",DmapTypeDefinition.RAW_TYPE),
		pcmt("pcmt","dpap.imagecomments",DmapTypeDefinition.STRING_TYPE),
		pimf("pimf","dpap.imagefilename",DmapTypeDefinition.STRING_TYPE),
		pifs("pifs","dpap.imagefilesize",DmapTypeDefinition.U_INT_TYPE),
		pfmt("pfmt","dpap.imageformat",DmapTypeDefinition.STRING_TYPE),
		plsz("plsz","dpap.imagelargefilesize",DmapTypeDefinition.U_LONG_TYPE),
		phgt("phgt","dpap.imagepixelheight",DmapTypeDefinition.U_INT_TYPE),
		pwth("pwth","dpap.imagepixelwidth",DmapTypeDefinition.U_INT_TYPE),
		prat("prat","dpap.imagerating",DmapTypeDefinition.U_INT_TYPE),
		ppro("ppro","dpap.protocolversion",DmapTypeDefinition.VERSION_TYPE),
		ipsa("ipsa","dpap.iphotoslideshowadvancedoptions", DmapTypeDefinition.CONTAINER_TYPE),
		pret("pret","dpap.retryids",DmapTypeDefinition.CONTAINER_TYPE),
		aels("aels", "com.apple.itunes.liked-state", DmapTypeDefinition.U_INT_TYPE),
		pfai("pfai", "dpap.failureids", DmapTypeDefinition.CONTAINER_TYPE),
		pemd("pemd", "com.apple.itunes.photos.modification-date", DmapTypeDefinition.DATE_TYPE),
		peki("peki", "com.apple.itunes.photos.key-image-id", DmapTypeDefinition.U_INT_TYPE),
		pefc("pefc", "com.apple.itunes.photos.faces", DmapTypeDefinition.CONTAINER_TYPE),
		peed("peed", "com.apple.itunes.photos.exposure-date", DmapTypeDefinition.DATE_TYPE),
		peak("peak", "com.apple.itunes.photos.album-kind", DmapTypeDefinition.U_INT_TYPE),
		ipsl("ipsl", "dpap.iphotoslideshowoptions", DmapTypeDefinition.CONTAINER_TYPE),
		ceVO("ceVO", "com.apple.itunes.unknown-voting", DmapTypeDefinition.U_BYTE_TYPE),
		aeml("aeml", "com.apple.itunes.media-kind-listing", DmapTypeDefinition.CONTAINER_TYPE),
		aemi("aemi", "com.apple.itunes.media-kind-listing-item", DmapTypeDefinition.CONTAINER_TYPE),
		ceQi("ceQi","unknown",DmapTypeDefinition.U_INT_TYPE),
		ceQh("ceQh","unknown",DmapTypeDefinition.STRING_TYPE),
		ceQk("ceQk","unknown",DmapTypeDefinition.STRING_TYPE),
		ceQm("ceQm","unknown",DmapTypeDefinition.U_INT_TYPE),
		ceQl("ceQl","unknown",DmapTypeDefinition.STRING_TYPE),
		ceQI("ceQI","unknown",DmapTypeDefinition.U_INT_TYPE),
		mscu("mscu","unknown-cu",DmapTypeDefinition.U_LONG_TYPE),
		cads("cads","unknown-ds",DmapTypeDefinition.U_INT_TYPE),
		cmik("cmik","unknown-ik",DmapTypeDefinition.U_BYTE_TYPE),
		cmnm("cmnm","unknown-nm",DmapTypeDefinition.STRING_TYPE),
		cmsp("cmsp","unknown-sp",DmapTypeDefinition.U_BYTE_TYPE),
		cmty("cmty","unknown-ty",DmapTypeDefinition.STRING_TYPE),
		agar("agar","unknown.ar",DmapTypeDefinition.CONTAINER_TYPE),
		caov("caov","unknown.ov",DmapTypeDefinition.U_BYTE_TYPE),
		cmpa("cmpa","unknown.pa",DmapTypeDefinition.CONTAINER_TYPE),
		cmrl("cmrl","unknown.rl",DmapTypeDefinition.U_BYTE_TYPE),
		caks("caks","unknown.ss",DmapTypeDefinition.U_BYTE_TYPE),
		cass("cass","unknown.ss",DmapTypeDefinition.U_BYTE_TYPE),
		casc("casc","unknown.ss",DmapTypeDefinition.U_BYTE_TYPE),
		cmsv("cmsv","unknown.sv",DmapTypeDefinition.U_BYTE_TYPE),
		ceSX("ceSX","unknown.sx",DmapTypeDefinition.U_LONG_TYPE);

		private final String shortname;
		private final String longname;
		private final DmapTypeDefinition type;

		DmapProtocolDefinition(String shortname, String longname, DmapTypeDefinition type)
		{
			this.shortname = shortname;
			this.longname = longname;
			this.type = type;
		}

		@Override
		public String getLongname()
		{
			return longname;
		}

		@Override
		public String getShortname()
		{
			return shortname;
		}

		@Override
		public DmapTypeDefinition getType()
		{
			return type;
		}
	}

	String getLongname();
	String getShortname();
	DmapTypeDefinition getType();
}
